src/Entity/AbstractCronTask.php
<?php

namespace ICS\CronBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping as ORM;
use ICS\CronBundle\Form\Type\CronTaskType;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpKernel\KernelInterface;

/**
 * @ORM\Entity
 * @ORM\Table(schema="cron")
 * @ORM\MappedSuperclass
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\HasLifecycleCallbacks()(
 */
abstract class AbstractCronTask
{
    /**
     * Undocumented variable.
     *
     * @var int
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;
    /**
     * @ORM\ManyToOne(targetEntity="ICS\CronBundle\Entity\Type\AbstractCronType",cascade = {"persist","remove"})
     */
    protected $cronType;
    /**
     * @ORM\Column(type="string")
     */
    protected $name = 'New Cron Task';
    /**
     * @ORM\Column(type="string")
     */
    protected $technicalName = 'Cron Task';
    /**
     * @ORM\Column(type="text",nullable=true)
     */
    protected $description = '';
    /**
     * @ORM\Column(type="text")
     */
    protected $technicalDescription = 'Cron Task Description';
    /**
     * @ORM\ManyToOne(targetEntity="ICS\CronBundle\Entity\CronGroup", inversedBy="tasks", cascade={"persist","remove"})
     */
    protected $group;
    /**
     * @ORM\OneToMany(targetEntity="ICS\CronBundle\Entity\Report\CronReport",mappedBy="cronTask", cascade={"persist","remove"})
     */
    protected $reports;

    private $doctrine;
    private $container;
    private $kernel;

    /**
     * { inherited }.
     */
    public function __construct(ContainerInterface $container, EntityManagerInterface $doctrine, KernelInterface $kernel)
    {
        $this->Initialize($container, $doctrine, $kernel);
        $this->reports = new ArrayCollection();
    }

    public function Initialize(ContainerInterface $container, EntityManagerInterface $doctrine, KernelInterface $kernel)
    {
        $this->container = $container;
        $this->kernel = $kernel;
        $this->doctrine = $doctrine;
    }

    /**
     * Undocumented function.
     */
    public function getNextExecution(): DateTime
    {
        return $this->getCronType()->getNextExecution();
    }

    /**
     * Undocumented function.
     */
    public function execute(): void
    {
    }

    /**
     * Get the value of id.
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the value of name.
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Get the value of technicalName.
     */
    public function getTechnicalName()
    {
        return $this->technicalName;
    }

    /**
     * Get the value of description.
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set the value of description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Set the value of name.
     *
     * @return self
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of technicalDescription.
     */
    public function getTechnicalDescription()
    {
        return $this->technicalDescription;
    }

    /**
     * Get the value of group.
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * Set the value of group.
     *
     * @return self
     */
    public function setGroup($group)
    {
        $this->group = $group;

        return $this;
    }

    /**
     * Get the value of doctrine.
     */
    public function getDoctrine()
    {
        return $this->doctrine;
    }

    /**
     * Get the value of container.
     */
    public function getContainer()
    {
        return $this->container;
    }

    /**
     * Get the value of kernel.
     */
    public function getKernel()
    {
        return $this->kernel;
    }

    /**
     * Get the value of cronType.
     */
    public function getCronType()
    {
        return $this->cronType;
    }

    /**
     * Set the value of cronType.
     *
     * @return self
     */
    public function setCronType($cronType)
    {
        $this->cronType = $cronType;

        return $this;
    }

    /**
     * Get the value of report.
     */
    public function getReports()
    {
        return $this->reports;
    }

    public function getFormType(): string
    {
        return CronTaskType::class;
    }

    public function getLastReport()
    {
        $result = null;
        $lastDate = null;
        foreach ($this->getReports() as $report) {
            if (null == $lastDate || $lastDate < $report->getDateEnd()) {
                $lastDate = $report->getDateEnd();
                $result = $report;
            }
        }

        return $result;
    }

    public function __toString()
    {
        return $this->name.' ('.get_class($this).')';
    }
}

src/Entity/Report/CronReport.php
<?php

namespace ICS\CronBundle\Entity\Report;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use ICS\CronBundle\Entity\AbstractCronTask;

/**
 * @ORM\Entity
 * @ORM\Table(schema="cron")
 */
class CronReport
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="datetime")
     */
    private $dateStart;
    /**
     * @ORM\Column(type="datetime")
     */
    private $dateEnd;

    /**
     * @ORM\ManyToOne(targetEntity="ICS\CronBundle\Entity\AbstractCronTask",inversedBy="reports", cascade={"persist","remove"})
     */
    private $cronTask;
    /**
     * @ORM\OneToMany(targetEntity="ICS\CronBundle\Entity\Report\CronReportLine",mappedBy="cronReport", cascade={"persist","remove"})
     * @ORM\OrderBy({"dateLine" = "ASC"})
     */
    private $lines;

    public function __construct()
    {
        $this->dateStart = new DateTime();
        $this->lines = new ArrayCollection();
    }

    public function addLine(CronReportLine $line): CronReport
    {
        if (!$this->lines->contains($line)) {
            $this->lines->add($line);
            $line->setCronReport($this);
        }

        return $this;
    }

    public function close(): void
    {
        $this->dateEnd = new DateTime();
    }

    /**
     * Get the value of id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Get the value of dateStart.
     */
    public function getDateStart(): DateTime
    {
        return $this->dateStart;
    }

    /**
     * Set the value of dateStart.
     *
     * @return self
     */
    public function setDateStart(DateTime $dateStart)
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    /**
     * Get the value of dateEnd.
     */
    public function getDateEnd(): DateTime
    {
        return $this->dateEnd;
    }

    /**
     * Set the value of dateEnd.
     *
     * @return self
     */
    public function setDateEnd(DateTime $dateEnd)
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    /**
     * Get the value of cronTask.
     */
    public function getCronTask(): AbstractCronTask
    {
        return $this->cronTask;
    }

    /**
     * Set the value of cronTask.
     *
     * @return self
     */
    public function setCronTask(AbstractCronTask $cronTask)
    {
        $this->cronTask = $cronTask;

        return $this;
    }

    public function getDuration()
    {
        return $this->dateStart->diff($this->dateEnd);
    }

    /**
     * Get the value of lines.
     */
    public function getLines()
    {
        return $this->lines;
    }

    public function getGlobalResult()
    {
        $result = CronReportLine::TYPE_SUCCESS;

        foreach ($this->lines as $line) {
            if (CronReportLine::TYPE_ERROR == $line->getType()) {
                $result = CronReportLine::TYPE_ERROR;
            } elseif (CronReportLine::TYPE_ERROR != $result && CronReportLine::TYPE_WARNING == $line->getType()) {
                $result = CronReportLine::TYPE_WARNING;
            }
        }

        return $result;
    }
}

src/Entity/Widgets/ReportListWidget.php
<?php

namespace ICS\CronBundle\Entity\Widgets;

use Doctrine\ORM\Mapping as ORM;
use ICS\DashboardBundle\Entity\Widget;
use Twig\Environment;

/**
 * @ORM\Table(schema="dashboard")
 * @ORM\Entity
 */
class ReportListWidget extends Widget
{
    public function __construct(Environment $twig)
    {
        parent::__construct($twig);
        $this->setWidth(6);
        $this->setHeight(6);
        $this->setBgColor("#14808B");
    }

    public function getJs()
    {
        if (null == $this->twig) {
            return '';
        }

        return $this->twig->render('@Cron/widgets/reportList.js.twig', ['widget' => $this]);
    }

    public function getUI()
    {
        if (null == $this->twig) {
            return '';
        }

        return $this->twig->render('@Cron/widgets/reportList.html.twig', ['widget' => $this]);
    }
}

src/Entity/Widgets/TaskListWidget.php
<?php

namespace ICS\CronBundle\Entity\Widgets;

use Doctrine\ORM\Mapping as ORM;
use ICS\DashboardBundle\Entity\Widget;
use Twig\Environment;

/**
 * @ORM\Table(schema="dashboard")
 * @ORM\Entity
 */
class TaskListWidget extends Widget
{
    public function __construct(Environment $twig)
    {
        parent::__construct($twig);
        $this->setWidth(6);
        $this->setHeight(6);
        $this->setBgColor("#14808B");
    }

    public function getJs()
    {
        if (null == $this->twig) {
            return '';
        }

        return $this->twig->render('@Cron/widgets/taskList.js.twig', ['widget' => $this]);
    }

    public function getUI()
    {
        if (null == $this->twig) {
            return '';
        }

        return $this->twig->render('@Cron/widgets/taskList.html.twig', ['widget' => $this]);
    }
}

templates/widgets/reportList.html.twig
{% extends "@Dashboard/widget.html.twig" %}

{% trans_default_domain('cron') %}

{% block content %}

<div id="rlwWidget-{{ widget.id }}" class="text-center">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h1><i class="fa fa-clipboard"></i><h1>
                <h2>{{ 'Report List'|trans }}</h2>
            </div>
        </div>
        <div class="row">
            <div id="reportList-{{ widget.id }}" class="col-12">

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/widgets/reportList.js.twig
<script>
$(document).ready(function(){


    getReportList_{{ widget.id }}();
    function getReportList_{{ widget.id }}()
    {
        $('#reportList-{{ widget.id }}').html('<div class="spinner-border spinner-border-sm" role="status"></div> ' + '{{ "Loading"|trans }}' + '...');
        $.ajax({
            url: '{{ path('ics-cron-report-list') }}',
            data: {
                'widgetId': {{ widget.id }}
            }
        }).done(function(data){
            $('#reportList-{{ widget.id }}').html(data);
        });

    }
});

</script>

templates/widgets/reportListResult.html.twig
{% trans_default_domain('cron') %}

{% if widget!=null %}
    <table class="table" style="color: {{ widget.textcolor }};">
{% else %}
    <table class="table">
{% endif %}
    <thead>
        <tr>
            <th>{{ "Status"|trans }}</th>
            <th>{{ "Task name"|trans }}</th>
            <th>{{ "Start date"|trans }}</th>
            <th>{{ "End date"|trans }}</th>
            <th>{{ "Duration"|trans }}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for report in reports %}

            {% if report.globalResult == 'danger' %}
                {% set icon = 'fa fa-exclamation-circle' %}
            {% elseif report.globalResult == 'warning' %}
                {% set icon = 'fa fa-exclamation-triangle' %}
            {% else %}
                {% set icon = 'fa fa-check-circle' %}
            {% endif %}

            <tr>
                <td title="{{ report.globalResult|trans }}"><i class="{{ icon }} text-{{ report.globalResult }}"></i></td>
                <td>
                    <a style="color: {{ widget.textcolor }};" href="{{ path('ics-cron-task-show',{ id: report.cronTask.id }) }}">
                       <i class="fa fa-cog"></i> {{ report.cronTask.name|trans }}
                    </a>
                </td>
                <td>{{ report.dateStart|date('d/m/Y H:i') }}</td>
                <td>{{ report.dateEnd|date('d/m/Y H:i') }}</td>
                <td>{{ report.duration|date('%i min %s sec %f µs') }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('ics-cron-report',{ id: report.id }) }}">
                        <i class="fa fa-eye"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

templates/widgets/taskList.html.twig
{% extends "@Dashboard/widget.html.twig" %}
{% trans_default_domain('cron') %}
{% block content %}

<div id="tlwWidget-{{ widget.id }}" class="text-center">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h1><i class="fa fa-cogs"></i><h1>
                <h2>{{ 'Task List'|trans }}</h2>
            </div>
        </div>
        <div class="row">
            <div id="taskList-{{ widget.id }}" class="col-12"></div>
        </div>
    </div>
</div>

{% endblock %}

templates/widgets/taskList.js.twig
<script>
$(document).ready(function(){


    getTaskList_{{ widget.id }}();
    function getTaskList_{{ widget.id }}()
    {
        $('#taskList-{{ widget.id }}').html('<div class="spinner-border spinner-border-sm" role="status"></div> ' + '{{ "Loading"|trans }}' + '...');
        $.ajax({
            url: '{{ path('ics-cron-task-list') }}',
            data: {
                'widgetId': {{ widget.id }}
            }
        }).done(function(data){
            $('#taskList-{{ widget.id }}').html(data);
        });

    }
});

</script>

templates/widgets/taskListResult.html.twig
{% trans_default_domain('cron') %}
<table class="table" style="color: {{ widget.textcolor }};">
<tr>
    <th>{{ 'Task name'|trans }}</th>
    <th>{{ 'Task type'|trans }}</th>
    <th>{{ 'Next execution'|trans }}</th>
    <th>{{ 'Last result'|trans }}</th>
    <th>{{ 'Last execution'|trans }}</th>
</tr>
{% for task in tasks %}
    <tr>
        <td class="text-start"><a style="color: {{ widget.textColor }};" href="{{ path('ics-cron-task-show',{ id: task.id}) }}"><i class="fa fa-cog"></i> {{ task.name|trans }}</a></td>
        <td>{{ task.cronType.clearName|trans }}</td>
        <td>{{ task.nextExecution|date('d/m/Y H:i',task.cronType.timezone) }}</td>
        <td class="">
            {% if task.lastReport %}
                 {% if task.lastReport.globalResult == 'danger' %}
                    {% set icon = 'fa fa-exclamation-circle' %}
                {% elseif task.lastReport.globalResult == 'warning' %}
                    {% set icon = 'fa fa-exclamation-triangle' %}
                {% else %}
                    {% set icon = 'fa fa-check-circle' %}
                {% endif %}
                <i class="{{ icon }}  text-{{ task.lastReport.globalResult }}"></i>
            {% else %}
                <i class="fa fa-ban"></i>
            {% endif %}
        </td>
        <td class="">
            {% if task.lastReport %}
                {{ task.lastReport.dateEnd|date('d/m/Y H:i',task.cronType.timezone) }}
            {% else %}
                <i class="fa fa-ban"></i>
            {% endif %}
        </td>
    </tr>
{% endfor %}

</table>
<div class="btn-group">
    <a href="{{ path('ics-cron-add') }}" class="btn btn-primary">
        <i class="fa fa-plus"></i> {{ 'Add Task'|trans }}
    </a>
</div>